version: '2'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: mysql-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - "3307:3306"